### ISSUE TITLE
Enable CI build for pull requests

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#107]
QA before merging patches is desired as broken patches come too often.

* [ ] select fast tests for all pull requests (eg. not convert)
* [ ] add some logic to also select tests if the pull request modifies certain sources (eg. convert)
* [ ] enable the CI integration
