### ISSUE TITLE
zoned mode: pre-release checklist

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#367]
Status: mkfs is usable for testing on top of null_blk

Remaining:
* [ ] report zone_unusable in 'btrfs fi df'
* [ ] verify automatic bg reclaim after filling and removing data
* [ ] tune output of mkfs, now it's 'zoned device' and the zone size has to be indented
* [ ] add entry to 'btrfs fi usage' overview, total zone_unusuable amount, same to the per device stats and also in 'btrfs dev usage'

Hints:
* null_blk
	* must be modprobed with nr_devices=0
	* use only nullbX device names and verify the size in lsblk output before testing
	* use 'blkzone report' to verify zone status
	* minimal device size is 2G for 256M zones
