### ISSUE TITLE
Generate preview of manual page after changes

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#824]
Changes to documentation should be also reviewable in the CI. Do it at least for the manual pages.

- [x] add CI job to generate manual pages
- [x] filter only the modified files
- [x] render the manual page to something that can be viewed either as plain text or formatted html
- [x] put the rendering to job summary (details tag, pre)
- [ ] update for more workflows

**Comment by kdave** [comment]
Copied from `mc` formatter, this seems to give a good result when viewed on terminal, but the actual output contains a lot of `^H` characters that emulate deletion and need to be handled.

```
COLUMNS=80 MANROFFOPT=-c MAN_KEEP_FORMATTING=1 man -P cat fsck.btrfs.8
```

**Comment by kdave** [comment]
This seems to work:

```
COLUMNS=80 man -P cat > file
```

```
FSCK.BTRFS(8)                        BTRFS                       FSCK.BTRFS(8)

NAME
       fsck.btrfs - do nothing, successfully

SYNOPSIS
       fsck.btrfs [-aApy] [<device>...]

DESCRIPTION
       fsck.btrfs  is  a  type of utility that should exist for any filesystem
       and is called during system setup when the corresponding /etc/fstab en‐
       tries contain non-zero value for fs_passno, see fstab(5) for more.

       Traditional filesystems need to run their respective  fsck  utility  in
       case  the  filesystem was not unmounted cleanly and the log needs to be
       replayed before mount. This is not needed for  BTRFS.  You  should  set
       fs_passno to 0.

       If  you wish to check the consistency of a BTRFS filesystem or repair a
       damaged filesystem, see btrfs-check(8). By default  filesystem  consis‐
       tency  is  checked,  the repair mode is enabled via the --repair option
       (use with care!).

OPTIONS
       The options are all the same and detect if fsck.btrfs  is  executed  in
       non-interactive mode and exits with success, otherwise prints a message
       about btrfs check.

EXIT STATUS
       There are two possible exit codes returned:

       0      No error

       8      Operational error, e.g. device does not exist

FILES
       /etc/fstab

SEE ALSO
       btrfs(8), fsck(8), fstab(5)

6.9                              Jun 19, 2024                    FSCK.BTRFS(8)
```

**Comment by kdave** [comment]
Now implemenetd for branch devel. Remaining is to do that for pull requests too once it's tested.

**Comment by kdave** [comment]
Won't be done for PR workflows, changes to manual pages are rare so it'd slow down testing. If needed use the `ci/name` branch that also runs the `devel` workflow but won't interfere with other changes.
