### ISSUE TITLE
Tracking issue: gcc + asan test coverage

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#92]
What tests pass with `make D=asan CC=gcc` build. The list is edited in-place, updates as comments.

- [x] test-cli
- [x] test-mkfs
   - [x] 009-special-files-for-rootdir - minor leak
- [x] test-misc
   - [x] 005-convert-progress-thread-crash - leaks
   - [x] 008-leaf-crossing-stripes - leaks
   - [x] 010-convert-delete-ext2-subvol - leaks
- [x] test-check
   - [x] 020-extent-ref-cases - heap overflow

**Comment by adam900710** [comment]
020 overflow fixed:
https://patchwork.kernel.org/patch/10218105/

**Comment by adam900710** [comment]
mkfs:  009-special-files-for-rootdir - minor leak fixed:
https://patchwork.kernel.org/patch/10218129/

**Comment by adam900710** [comment]
misc: 008
https://patchwork.kernel.org/patch/10218147/

**Comment by kdave** [comment]
Excellent, thanks. Patches applied. I'll do the pre-release asan checks on my machine, the travis CI would need more work to get that automated, but that's for another issue.
